serial_control:
  unix_socket: "/home/coolpi/arduino"
  port: "/dev/ttyACM0"
camera:
  # - {
  #     unix_socket: "/home/coolpi/uds_socket_distance",
  #     to_do: "distance",
  #     camera_id: "0",
  #   }
  - {
      unix_socket: "/home/coolpi/uds_socket_near",
      to_do: "near",
      camera_id: "0",
    }
  # - {
  #     unix_socket: "/home/coolpi/uds_socket_work",
  #     to_do: "work",
  #     camera_id: "4",
  #   }
other:
  distaice_long: 60   #cm
  position: 2    #1 左边  2 右边



