unix_socket: 
  run1: '/home/coolpi/uds_socket_run1'
  run2: '/home/coolpi/uds_socket_run2'
  work: '/home/coolpi/uds_socket_work'
serial_control:
  port: '/dev/ttyACM0'
camera:
    - {unix_socket: '/home/coolpi/uds_socket_run1',to_do: 'run1',camera_id: '0'}
    - {unix_socket: '/home/coolpi/uds_socket_run2',to_do: 'run2',camera_id: '2'}
    - {unix_socket: '/home/coolpi/uds_socket_work',to_do: 'work',camera_id: '4'}

# unix_socket: 
#   run: '/Users/carlos/uds_socket_run'
#   work: '/Users/carlos/uds_socket_work'