unix_socket: 
  run: '/home/coolpi/uds_socket_run'
  work: '/home/coolpi/uds_socket_work'
serial_control:
  port: '/dev/ttyACM0'
# unix_socket: 
#   run: '/Users/carlos/uds_socket_run'
#   work: '/Users/carlos/uds_socket_work'