unix_socket: 
  run1: '/home/coolpi/uds_socket_run1'
  run2: '/home/coolpi/uds_socket_run2'
  work: '/home/coolpi/uds_socket_work'
serial_control:
  port: '/dev/ttyACM0'
# unix_socket: 
#   run: '/Users/carlos/uds_socket_run'
#   work: '/Users/carlos/uds_socket_work'