camera:
- camera_id: '0'
  to_do: distance
  unix_socket: /home/coolpi/uds_socket_distance
other:
  distaice_long: '602'
  position: 1
serial_control:
  port: /dev/ttyACM0
  unix_socket: /home/coolpi/arduino
