serial_control:
  unix_socket: "/home/coolpi/arduino"
  port: "/dev/ttyACM0"
camera:
  - {
      unix_socket: "/home/coolpi/uds_socket_run1",
      to_do: "run1",
      camera_id: "0",
    }
  - {
      unix_socket: "/home/coolpi/uds_socket_run2",
      to_do: "run2",
      camera_id: "2",
    }
  - {
      unix_socket: "/home/coolpi/uds_socket_work",
      to_do: "work",
      camera_id: "4",
    }
